# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      company_name:
        description: "Name of company"
        required: false
        default: 'puppy'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: install gem dependencies
      run: bundle install
      
    - name: customize an already built ios app
      run: bundle exec fastlane ios customize_built_app
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VAULT_APPROLE_ROLE_ID: ${{ secrets.VAULT_CODESIGNING_ROLE_ID }}
        VAULT_APPROLE_SECRET_ID: ${{ secrets.VAULT_CODESIGNING_SECRET_ID }}
